name: npm.build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # -------- server --------

      - name: Install server dependencies
        run: npm i
        working-directory: server

      - name: Lint server
        run: npm run lint
        working-directory: server

      - name: Test server
        run: npm run test
        working-directory: server

      # -------- client --------

      - name: Install client dependencies
        run: npm i
        working-directory: client

      - name: Build client
        run: npm run build
        working-directory: client
