name: Lint

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # ---------- server ----------

      - name: Install server dependencies
        run: npm i
        working-directory: server

      - name: Lint server
        run: npm run lint
        working-directory: server

      # ---------- client ----------

      - name: Install client dependencies
        run: npm i
        working-directory: client

